/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CafmActualForecastChart: typeof import('./src/components/cafm/CafmActualForecastChart.vue')['default']
    CafmBarChart: typeof import('./src/components/cafm/CafmBarChart.vue')['default']
    CafmCandlestickChart: typeof import('./src/components/cafm/CafmCandlestickChart.vue')['default']
    CafmCategoryFunnel: typeof import('./src/components/cafm/CafmCategoryFunnel.vue')['default']
    CafmDonutChart: typeof import('./src/components/cafm/CafmDonutChart.vue')['default']
    CafmForecastChart: typeof import('./src/components/cafm/CafmForecastChart.vue')['default']
    CafmMaintenanceCostChart: typeof import('./src/components/cafm/CafmMaintenanceCostChart.vue')['default']
    CafmMultiBarChart: typeof import('./src/components/cafm/CafmMultiBarChart.vue')['default']
    CafmNumberCard: typeof import('./src/components/cafm/CafmNumberCard.vue')['default']
    CafmPreventiveCalendar: typeof import('./src/components/cafm/CafmPreventiveCalendar.vue')['default']
    CafmSeriesChart: typeof import('./src/components/cafm/CafmSeriesChart.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
